The wise Beaver's big dam of logs: 
---------------------------------------
__main__: Sent message: LoaderTaskType.LOAD
---------------------------------------
BlackBox-2: Start of service
---------------------------------------
Loader: Start of service
---------------------------------------
Loader: Recieved message: LoaderTaskType.LOAD
---------------------------------------
Loading 5 more images
---------------------------------------
    - Loaded ../img/test/1.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/2.jpg
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/3.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/4.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: LoaderAnswerType.NOMORE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.NOMORE
---------------------------------------
Loader: Sent message: LoaderAnswerType.LOADDONE
---------------------------------------
__main__: Sent message: LoaderTaskType.TERMINATE
---------------------------------------
Loader: Recieved message: LoaderTaskType.TERMINATE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.LOADDONE
---------------------------------------
Loader: Sent message: LoaderAnswerType.END
---------------------------------------
Loader: End of service
---------------------------------------
__main__: Recieved message: LoaderAnswerType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
__main__: Sent message: TaskType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.END
---------------------------------------
__main__: End of service
---------------------------------------
BlackBox-2: Sent message: AnswerType.BOXENDSERVICE
---------------------------------------
BlackBox-2: End of service
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 87, in printResults
    pprint(Fore.YELLOW+Style.BRIGHT+str(results)+Style.RESET_ALL)
TypeError: 'module' object is not callable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 89, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 95, in getPrintElement
    for i in indent: indentStr += '    '
TypeError: 'int' object is not iterable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 101, in getPrintElement
    msg += Herald.getPrintElement(key, element[key])
TypeError: getPrintElement() missing 1 required positional argument: 'indent'

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 149, in compute
    dataShoes = DataFormatter.getNoneData()
TypeError: getNoneData() missing 2 required positional arguments: 'refProd' and 'imgName'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 122, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 145, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 89, in printResults
    msg += Herald.getPrintElement(key, results[key], indent)+',\n'
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 114, in getPrintElement
    else: msg+=element
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 145, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 89, in printResults
    msg += Herald.getPrintElement(key, results[key], indent)+',\n'
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 114, in getPrintElement
    else: msg+=element
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 152, in compute
    dataShoesJson = json.dumps(dataShoes)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 152, in compute
    dataShoesJson = json.dumps(dataShoes)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 152, in compute
    dataShoesJson = json.dumps(dataShoes)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Esteban\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 122, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 122, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 81, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 123, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range
