The wise Beaver's big dam of logs: 
---------------------------------------
__main__: Sent message: LoaderTaskType.LOAD
---------------------------------------
BlackBox-2: Start of service
---------------------------------------
Loader: Start of service
---------------------------------------
Loader: Recieved message: LoaderTaskType.LOAD
---------------------------------------
Loading 5 more images
---------------------------------------
    - Loaded ../img/test/1.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/2.jpg
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/3.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
    - Loaded ../img/test/4.jpg
---------------------------------------
Loader: Sent message: TaskType.PROCESS
---------------------------------------
Loader: Sent message: LoaderAnswerType.NOMORE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.NOMORE
---------------------------------------
Loader: Sent message: LoaderAnswerType.LOADDONE
---------------------------------------
__main__: Sent message: LoaderTaskType.TERMINATE
---------------------------------------
Loader: Recieved message: LoaderTaskType.TERMINATE
---------------------------------------
__main__: Recieved message: LoaderAnswerType.LOADDONE
---------------------------------------
Loader: Sent message: LoaderAnswerType.END
---------------------------------------
Loader: End of service
---------------------------------------
__main__: Recieved message: LoaderAnswerType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.PROCESS
---------------------------------------
__main__: Sent message: TaskType.END
---------------------------------------
BlackBox-2: New data written in the test output file.
---------------------------------------
BlackBox-2: Recieved message: TaskType.END
---------------------------------------
__main__: End of service
---------------------------------------
BlackBox-2: Sent message: AnswerType.BOXENDSERVICE
---------------------------------------
BlackBox-2: End of service
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 87, in printResults
    pprint(Fore.YELLOW+Style.BRIGHT+str(results)+Style.RESET_ALL)
TypeError: 'module' object is not callable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 89, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoesJson)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 91, in printResults
    msg += Herald.getPrintElement(key, results[key])
TypeError: string indices must be integers

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 95, in getPrintElement
    for i in indent: indentStr += '    '
TypeError: 'int' object is not iterable

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 77, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 167, in compute
    Herald.printResults(dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 90, in printResults
    msg += Herald.getPrintElement(key, results[key], 1)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\utilities\Herald.py", line 101, in getPrintElement
    msg += Herald.getPrintElement(key, element[key])
TypeError: getPrintElement() missing 1 required positional argument: 'indent'

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 16, in writeDataToTempFile
    outputFilePath = (os.join(tempDir, procName+'.json'))
AttributeError: module 'os' has no attribute 'join'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 18, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp\\BlackBox-2.json'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp\\BlackBox-2.json'

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-4.json'

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-2.json'

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 146, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\interface\Writer.py", line 19, in writeDataToTempFile
    with open(outputFilePath, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../out/temp/BlackBox-3.json'

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-4 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\BlackBox.py", line 119, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "C:\Users\Esteban\Documents\GitHub\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range

---------------------------------------
No blackboxes are running. Politely stopping the program.
---------------------------------------
BlackBox-2 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 147, in compute
    Writer.writeDataToTempFile(self.name, dataShoes)
UnboundLocalError: local variable 'dataShoes' referenced before assignment

---------------------------------------
BlackBox-3 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 147, in compute
    <<<<<<< HEAD
UnboundLocalError: local variable 'dataShoes' referenced before assignment

---------------------------------------
BlackBox-5 encountered an error, and stopped its execution. See the error below: 

---------------------------------------
Traceback (most recent call last):
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 80, in run
    self.compute(nextTask.img, nextTask.imgPath, nextTask.imgPathInCache, nextTask.tfImg, modelShoeDetector)
  File "D:\Python projects\projet-i3-sneaker\src\BlackBox.py", line 122, in compute
    (mainColor, secondaryColor) = ColorDetector.detection(
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 320, in detection
    ColorDetector.persistanceColor(res)
  File "D:\Python projects\projet-i3-sneaker\src\blackBoxModules\colorDetector\ColorDetector.py", line 249, in persistanceColor
    deuxiemeElem = str([*keys][1])
IndexError: list index out of range
